host: https://api.tally.projects.hogt.me/tally/api
auth: token
verbose: false
gameTag: mcj
index: ""
#summaryUrl: https://api.tally.projects.hogt.me/tally/api/summary/instance?instance={INSTANCE}
max_retries: 3